In [1]:
import numpy as np

marks = np.random.randint(0, 101, 50)

print(marks)

[ 23   0  26  44  52  77  76  64  23  28  53  57  86  97  32  44 100   1
  41   8  39  48  29  31  22  84   7  10   9  71  13  14  79  59  79  72
  92  13  73  24  85  28  65  67  34  31  47  97  53  97]


In [2]:
import numpy as np

marks = np.random.randint(0, 101, 50)

print("Total =", np.sum(marks))
print("Average =", np.mean(marks))
print("Highest =", np.max(marks))
print("Lowest =", np.min(marks))

Total = 2506
Average = 50.12
Highest = 100
Lowest = 0


In [3]:
import numpy as np

marks = np.random.randint(0, 101, 50)

print("Above 75 =", np.sum(marks > 75))
print("Below 35 =", np.sum(marks < 35))
print("Between 35 and 75 =",
      np.sum((marks >= 35) & (marks <= 75)))

Above 75 = 14
Below 35 = 15
Between 35 and 75 = 21


In [4]:
import numpy as np

marks = np.array([95, 80, 65, 50, 30])

for i in marks:
    if i >= 75:
        print(i, "A")
    elif i >= 60:
        print(i, "B")
    elif i >= 35:
        print(i, "C")
    else:
        print(i, "Fail")

95 A
80 A
65 B
50 C
30 Fail


In [5]:
import numpy as np

marks = np.random.randint(0, 101, 50)

print(np.sort(marks)[-5:])

[90 94 95 98 99]


In [6]:
import numpy as np

marks = np.random.randint(0, 101, 50)

print(np.sort(marks)[:5])

[ 0  2 10 12 14]


In [7]:
import numpy as np

marks = np.random.randint(0, 101, 50)

print("Median =", np.median(marks))
print("Standard Deviation =", np.std(marks))

Median = 51.0
Standard Deviation = 28.948340194214936


In [8]:
import numpy as np

marks = np.random.randint(35, 101, (5, 5))

print("Marks Matrix:")
print(marks)

print("Total of each student:")
print(np.sum(marks, axis=1))

Marks Matrix:
[[73 96 66 79 98]
 [68 67 78 43 50]
 [35 48 94 63 98]
 [67 55 85 47 95]
 [49 62 72 85 53]]
Total of each student:
[412 306 338 349 321]


In [9]:
import numpy as np

marks = np.random.randint(35, 101, (5, 5))

print("Marks Matrix:")
print(marks)

print("Highest Marks in Each Subject:")
print(np.max(marks, axis=0))

Marks Matrix:
[[100  91  97  50  81]
 [100  58  59  51  47]
 [ 64  59  43  59  94]
 [ 48  86  65  86  71]
 [ 60  99  55  41  56]]
Highest Marks in Each Subject:
[100  99  97  86  94]


In [10]:
import numpy as np

marks = np.random.randint(35, 101, (5, 5))

for i in range(5):
    total = np.sum(marks[i])
    avg = np.mean(marks[i])
    per = avg

    if per >= 75:
        grade = "A"
    elif per >= 60:
        grade = "B"
    elif per >= 35:
        grade = "C"
    else:
        grade = "Fail"

    print("Student", i + 1)
    print("Marks =", marks[i])
    print("Total =", total)
    print("Average =", avg)
    print("Percentage =", per)
    print("Grade =", grade)
    print()

Student 1
Marks = [77 48 53 61 65]
Total = 304
Average = 60.8
Percentage = 60.8
Grade = B

Student 2
Marks = [55 77 42 70 68]
Total = 312
Average = 62.4
Percentage = 62.4
Grade = B

Student 3
Marks = [54 87 39 56 73]
Total = 309
Average = 61.8
Percentage = 61.8
Grade = B

Student 4
Marks = [64 77 55 47 37]
Total = 280
Average = 56.0
Percentage = 56.0
Grade = C

Student 5
Marks = [97 90 72 62 60]
Total = 381
Average = 76.2
Percentage = 76.2
Grade = A

